version: "3.1"
services:
  postgresdb:
    image: postgres:latest
    ports:
      - 5430:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: asana123
      POSTGRES_USER: postgres
    volumes:
      - data:/data/db
  rediscache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes: 
      - cache:/data
volumes:
  data:
  cache:
    driver: local