version: "3.1"
services:
  postgresdb:
    image: postgres:latest
    ports:
      - 5430:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: asana123
      POSTGRES_USER: postgres
    volumes:
      - data:/data/db
  rediscache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  data:
  cache:
    driver: local